language: node_js
node_js:
- '6'
- '8'
deploy:
  provider: npm
  email: banyudu@gmail.com
  api_key:
    secure: gQ0BzSF+2pQqgV0haJu0HrDnP1MxUbBhR3pDJLB81dKbIig5JIz4iWqXLY79/1C4TlUBDZwY6oIdwk/hcmt/YrOY1/OQpiFlPGc+/LLrmFKfS8U30REGO47+n3xOC/tIRzvO/KbnQ6wyF+XGfbjH3TwCjlDHZHI2b1Ma4++Bo+kGOJI4Cg3q6XMcTcJ64ZzRuk6Ln3OgeVm6sB2M7NWbXLJRII1MXYyg+W/6lZ5P3QfeyYHivkEbQWaKoCqmo1AckyIJ1HXSAgase3F4XsJ/5VoL3ot9Cviw9SVWBhD18V+G1cNcK6mFCabnbsH3cK8l0mHohkhvYX5JPGE2C3WuYlmU23xWrQ9DneAhdWkB6yfQBNKIkiXtKirRnEGDeB/1b1GOzGRWxnnu7t19485TyjbaHX4x6L2CjlzFLcAh0aDoTc9PjaBsBNcGuh1l3MdhG0zPRaeiFmLSVFBWTL91lOmW7N9g7kRzhPXWyjLwkuL8gJL2QyVkUJknE8PYvo33KbNskMkaQRpXTlXf7lR8pEwKW8vY1jlelBHDhv/2zo0w0l7NAoC2feIH0iWCNT7X75idhGSht7muZJPSNdT52qPrOmFgBMmg7089Yq8tTRnES1WewivnTaCWlBUeMAZ9EmYJb+Htr6UiVImuGlJtGsaCwPSDtl1Bq/xZWdYO3Ho=
  on:
    tags: true
    branch: master
  tag: latest
